[Params]
  description = "Projektemacher URL Shortener"
  disableScale = true
  copyrightYears = "2023 - 2026"

  [Params.Terminal]
    scheme = "shell-retro"
    userName = "projektemacher"
    pcName = "äh.xyz"
    workDir = "resolver"
    profile = "intro.txt"
    description = "/description.md"
    wikidata = false
    debug = false

  [Params.Tree]
    use = true
    folderName = "site"
    files = [
      ["Start", "/en"],
      ["Deutsche Übersetzung", "/de/"],
      ["Links", "/links/"],
      ["About", "/about/"],
      ["Projektemacher", "http://projektemacher.org/"],
      ["Projektemacher Labs", "https://labs.projektemacher.org/"]
    ]

  [Params.Navbar]
    use = false
